#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmspub
Version  : 0.1.4
Release  : 2
URL      : https://dev-www.libreoffice.org/src/libmspub-0.1.4.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libmspub-0.1.4.tar.xz
Summary  : Library for parsing the Microsoft Publisher file format structure
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libmspub-bin
Requires: libmspub-lib
Requires: libmspub-license
BuildRequires : boost-dev
BuildRequires : doxygen
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(zlib)

%description
libmspub is a library and a set of tools for reading and converting MS
Publisher files.

%package bin
Summary: bin components for the libmspub package.
Group: Binaries
Requires: libmspub-license

%description bin
bin components for the libmspub package.


%package dev
Summary: dev components for the libmspub package.
Group: Development
Requires: libmspub-lib
Requires: libmspub-bin
Provides: libmspub-devel

%description dev
dev components for the libmspub package.


%package doc
Summary: doc components for the libmspub package.
Group: Documentation

%description doc
doc components for the libmspub package.


%package lib
Summary: lib components for the libmspub package.
Group: Libraries
Requires: libmspub-license

%description lib
lib components for the libmspub package.


%package license
Summary: license components for the libmspub package.
Group: Default

%description license
license components for the libmspub package.


%prep
%setup -q -n libmspub-0.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534631843
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534631843
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libmspub
cp COPYING.MPL %{buildroot}/usr/share/doc/libmspub/COPYING.MPL
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pub2raw
/usr/bin/pub2xhtml

%files dev
%defattr(-,root,root,-)
/usr/include/libmspub-0.1/libmspub/MSPUBDocument.h
/usr/include/libmspub-0.1/libmspub/libmspub.h
/usr/lib64/libmspub-0.1.so
/usr/lib64/pkgconfig/libmspub-0.1.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libmspub/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmspub-0.1.so.1
/usr/lib64/libmspub-0.1.so.1.0.4

%files license
%defattr(-,root,root,-)
/usr/share/doc/libmspub/COPYING.MPL
